/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as helpers from "../helpers.js";
import type * as http from "../http.js";
import type * as v1_activities from "../v1/activities.js";
import type * as v1_feedback from "../v1/feedback.js";
import type * as v1_files from "../v1/files.js";
import type * as v1_invites from "../v1/invites.js";
import type * as v1_members from "../v1/members.js";
import type * as v1_orbits from "../v1/orbits.js";
import type * as v1_proUsers from "../v1/proUsers.js";
import type * as v1_teams from "../v1/teams.js";
import type * as v1_user from "../v1/user.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  helpers: typeof helpers;
  http: typeof http;
  "v1/activities": typeof v1_activities;
  "v1/feedback": typeof v1_feedback;
  "v1/files": typeof v1_files;
  "v1/invites": typeof v1_invites;
  "v1/members": typeof v1_members;
  "v1/orbits": typeof v1_orbits;
  "v1/proUsers": typeof v1_proUsers;
  "v1/teams": typeof v1_teams;
  "v1/user": typeof v1_user;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
