/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as app_activities from "../app/activities.js";
import type * as app_feedback from "../app/feedback.js";
import type * as app_files from "../app/files.js";
import type * as app_invites from "../app/invites.js";
import type * as app_members from "../app/members.js";
import type * as app_orbits from "../app/orbits.js";
import type * as app_teams from "../app/teams.js";
import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as emails from "../emails.js";
import type * as helpers from "../helpers.js";
import type * as http from "../http.js";
import type * as proUsers from "../proUsers.js";
import type * as user from "../user.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "app/activities": typeof app_activities;
  "app/feedback": typeof app_feedback;
  "app/files": typeof app_files;
  "app/invites": typeof app_invites;
  "app/members": typeof app_members;
  "app/orbits": typeof app_orbits;
  "app/teams": typeof app_teams;
  auth: typeof auth;
  crons: typeof crons;
  emails: typeof emails;
  helpers: typeof helpers;
  http: typeof http;
  proUsers: typeof proUsers;
  user: typeof user;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
