export const ACTIVE = "Active";
export const PAUSED = "Paused";
export const IDEA = "Idea";
export const PRAISE = "Praise";
export const OTHER = "Other";
export const ISSUE = "Issue";
export const EVERYDAY = "Everyday";
export const THRICE_A_WEEK = "Thrice A week";
export const ONEC_A_WEEK = "Once A Week";
